# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('productId', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('manufacturer', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('Zoomlens', models.CharField(max_length=50)),
                ('wireless', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('productId', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('manufacturer', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('screensize', models.CharField(max_length=60)),
                ('battery_life', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
