# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
