# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_display', '0003_auto_20160416_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
