# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_display', '0005_auto_20160416_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='image',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='name',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='price',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='productId',
        ),
    ]
