# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_display', '0007_auto_20160416_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
