# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_display', '0008_category_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'productId']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
    ]
